# Generated by Django 3.0 on 2020-06-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='friends',
            field=models.ManyToManyField(
                blank=True, related_name='_contact_friends_+', to='chat.Contact'),
        ),
    ]
